CREATE TABLE (
    id INT NOT NULL AUTO_INCREMENT,
    product VARCHAR(200) NOT NULL,
    price INT NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE (id INT NOT NULL AUTO_INCREMENT, product VARCHAR(200) NOT NULL, price INT NOT NULL, PRIMARY KEY(id));